sudo: true
language: cpp
compiler: gcc
dist: trusty

addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-7

# TODO: Write a proper makefile, clean this mess up.
script: g++-7 -w -std=c++17 fixup_iterators.cpp
